.TH man 1 "2022-10-11" "1.0.0" "Utilities for OMEMO media sharing"
.SH NAME
omemo-utils - Utilities for OMEMO media sharing
.SH SYNOPSIS
.B omut
[\-d] [\-o FILE] URL
.SH DESCRIPTION
.B omemo-utils
 are utilities for OMEMO media sharing.
The binary is called omut.
By default the downloaded file will be send to standard output.
.br
.SH OPTIONS
.TP
.BI "\-d"
Enable debug output.
.br
.TP
.BI "\-o FILE"
Redirect the output to a file.
.SH BUGS
Bugs can be reported by raising an issue at the Github issue tracker:
.br
.PP
<https://github.com/wstrm/omemo-utils/issues>
.br
.SH AUTHOR
Copyright (C) 2020 \- 2022  William Wennerström <william@wstrm.dev>.
.br
Licensed under MIT.
.br
.br
Man page is written by Michael Vetter <jubalh@iodoru.org>.
